/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppBanquetsRouteImport } from './routes/_app/banquets'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppProcurementRouteImport } from './routes/_app/procurement'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppBanquetsIdRouteImport } from './routes/_app/banquets.$id'
import { Route as PrintBanquetIdRouteImport } from './routes/print.banquet.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBanquetsRoute = AppBanquetsRouteImport.update({
  id: '/banquets',
  path: '/banquets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppBanquetsIdRoute = AppBanquetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBanquetsRoute,
} as any)
const PrintBanquetIdRoute = PrintBanquetIdRouteImport.update({
  id: '/print/banquet/$id',
  path: '/print/banquet/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/banquets': typeof AppBanquetsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/procurement': typeof AppProcurementRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/banquets/$id': typeof AppBanquetsIdRoute
  '/print/banquet/$id': typeof PrintBanquetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/banquets': typeof AppBanquetsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/procurement': typeof AppProcurementRoute
  '/recipes': typeof AppRecipesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/banquets/$id': typeof AppBanquetsIdRoute
  '/print/banquet/$id': typeof PrintBanquetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/banquets': typeof AppBanquetsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/banquets/$id': typeof AppBanquetsIdRoute
  '/print/banquet/$id': typeof PrintBanquetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/banquets'
    | '/dashboard'
    | '/integrations'
    | '/inventory'
    | '/procurement'
    | '/recipes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/banquets/$id'
    | '/print/banquet/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/banquets'
    | '/dashboard'
    | '/integrations'
    | '/inventory'
    | '/procurement'
    | '/recipes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/banquets/$id'
    | '/print/banquet/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/setup'
    | '/_app/banquets'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/inventory'
    | '/_app/procurement'
    | '/_app/recipes'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/staff'
    | '/_app/banquets/$id'
    | '/print/banquet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  PrintBanquetIdRoute: typeof PrintBanquetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/banquets': {
      id: '/_app/banquets'
      path: '/banquets'
      fullPath: '/banquets'
      preLoaderRoute: typeof AppBanquetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banquets/$id': {
      id: '/_app/banquets/$id'
      path: '/$id'
      fullPath: '/banquets/$id'
      preLoaderRoute: typeof AppBanquetsIdRouteImport
      parentRoute: typeof AppBanquetsRoute
    }
    '/print/banquet/$id': {
      id: '/print/banquet/$id'
      path: '/print/banquet/$id'
      fullPath: '/print/banquet/$id'
      preLoaderRoute: typeof PrintBanquetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBanquetsRouteChildren {
  AppBanquetsIdRoute: typeof AppBanquetsIdRoute
}

const AppBanquetsRouteChildren: AppBanquetsRouteChildren = {
  AppBanquetsIdRoute: AppBanquetsIdRoute,
}

const AppBanquetsRouteWithChildren = AppBanquetsRoute._addFileChildren(
  AppBanquetsRouteChildren,
)

interface AppRouteChildren {
  AppBanquetsRoute: typeof AppBanquetsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppStaffRoute: typeof AppStaffRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBanquetsRoute: AppBanquetsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppStaffRoute: AppStaffRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  PrintBanquetIdRoute: PrintBanquetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
